name: Build
on:
  push:
    branches:
      - main

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install -r requirements.txt
      - run: ./dev/create-site-data.py --sheet $GOOGLE_SHEETS_ID --dir $SFS_DIR
      - run: cp ./dev/data.json ./assets/data/data.json
  build-and-serve:
    needs: data
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 19
    - run: npm ci
    - run: npm run lint
    # - run: npm test
    - run: npm run build
    # - run: npm run serve
